/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: 'jit',
  safelist: [
    'bg-gray-800',
    'group-hover:bg-primary/10',
    'dark:text-white-dark',
    'dark:border-white-dark/50',
    'group-hover:text-primary',
    'space-y-2.5',
    'rtl:space-x-reverse',
    'border-t',
    'border-black',
    'dark:border-white-dark',
    'w-1/5',
    'mx-auto',
    'my-6',
    'group-hover:border-primary',
    'group',
    'hover:border-primary',
    'border-black',
    'space-y-4',
    'max-h-0',
    'max-h-screen',
    'bg-success/20',
    'bg-info/20',
    'mt-10',
    '-bottom-12',
    ' h-24',
    ' w-24',
    ' ltr:-right-12',
    ' rtl:-left-12',
    'from-fuchsia-500',
    'to-fuchsia-400',
    'from-violet-500',
    'to-violet-400',
    'border-white',
    'dark:border-dark',
    'bg-[#bfc9d4]',
    'group-hover:opacity-100',
    'dark:bg-dark',
    'group-hover:-space-x-2',
    ' rtl:space-x-reverse',
    ' rtl:group-hover:space-x-reverse',
    'bg-danger/20',
    'group',
    'dark:bg-dark-light/10',
    'h-2.5',
    'from-[#1e9afe]',
    'to-[#60dfcd]',
    'pb-8',
    'from-[#3d38e1]',
    'to-[#1e9afe]',
    'ring-2',
    ' ring-white-light',
    ' ltr:mr-4',
    ' rtl:ml-4',
    ' dark:ring-dark',
    'media-aside',
    'align-self-start',
    'bg-success/30',
    ' hover:shadow-[0_10px_20px_-10px]',
    ' hover:shadow-success',
    'pb-8',
    '-mx-5',
    '-m-5',
    'dark:border-[#1b2e4b]',
    'ring-2',
    ' ring-white-light',
    ' ltr:mr-4',
    ' rtl:ml-4',
    ' dark:ring-dark',
    'from-[#fe5f75]',
    ' to-[#fc9842]',
    'from-[#a71d31]',
    ' to-[#3f0d12]',
    'from-[#009ffd]',
    'to-[#2a2a72]',
    'before:absolute',
    'before:inset-y-0',
    'before:m-auto',
    'before:h-2',
    'before:w-2',
    'before:rounded-full',
    'before:bg-white',
    'ltr:before:right-0.5',
    'rtl:before:left-0.5',
    'shadow-3xl',
    'dark:bg-dark-light/10',
    'dark:shadow-none',
    'w-summary-info',
    'rounded-xl',
    'bg-danger/10',
    'dark:bg-danger',
    'flex-initial',
    'dark:bg-primary',
    '!h-[360px]',
    'space-y-7',
    'shadow-secondary',
    'before:absolute',
    ' before:left-4',
    ' before:top-10',
    ' before:h-[calc(100%-24px)]',
    ' before:w-[2px] before:bg-white-dark/30',

    'shadow-[0_0_2px_0_#bfc9d4]',
    ' hover:bg-[#1937cc]',
    ' ltr:mr-2',
    ' rtl:ml-2',
    'shadow-[0_0_2px_0_#bfc9d4]',
    'hover:bg-[#1937cc]',
    'shadow-[0_0_2px_0_#bfc9d4]',
    'hover:bg-[#4361ee]',
    'bg-[#4361ee]',
    'text-[#d3d3d3]',
    'z-[7]',
    'mb-16',
    'text-white-light',
    'before:absolute',
    ' before:-right-44',
    ' before:bottom-0',
    ' before:top-0',
    ' before:m-auto',
    ' before:h-96',
    ' before:w-96',
    ' before:rounded-full',
    ' before:bg-[#1937cc]',
    'ltr:ml-5',
    'rtl:mr-5',
    'to-[#8058CA]',
    ' before:absolute',
    ' before:inset-y-0',
    ' before:m-auto',
    ' before:h-2',
    ' before:w-2',
    ' before:rounded-full',
    ' before:bg-white',
    ' ltr:before:right-0.5',
    ' rtl:before:left-0.5',
    'my-10',
    'text-[#e95f2b]',
    'dark:text-white-light',
    'btn-success',
    'text-[#515365]',
    'dark:text-white',
    'bg-[#1b2e4b]',
    'before:inline-block',
    ' before:h-1.5',
    ' before:w-1.5',
    ' before:rounded-full',
    ' before:bg-white',
    'space-y-1',
    'm-auto',

    'hover:opacity-80',
    'border-white/50',
    'bg-black/50',
    'mb-6',
    'min-h-[190px]',
    'from-[#4361ee]',
    'to-[#160f6b]',
    'whitespace-pre',
    'px-1',
    'dark:text-gray-500',
    'px-3',
    'dark:bg-success',
    'space-y-6',
    'bg-info',
    'bg-secondary',
    'group-hover:opacity-100',
    'badge-outline-primary',
    'bg-primary-light',
    'badge-outline-dark',
    'badge-outline-warning',
    'bg-dark-light',
    'bg-warning-light',
    'badge-outline-info',
    'bg-info-light',
    'badge-outline-secondary',
    'bg-secondary-light',
    'h-1.5',
    'w-1.5',
    'bg-black',
    'bg-warning',
    '!h-[290px]',
    'dark:bg-[#1b2e4b]',
    'from-[#7579ff]',
    'to-[#b224ef]',
    'ltr:mr-3',
    'rtl:ml-3',
    'space-y-9',

    'bg-secondary-light',
    'text-secondary',
    'dark:bg-secondary',
    'dark:text-secondary-light',
    'dark:bg-[#1b2e4b]',
    'from-[#3cba92]',
    'to-[#0ba360]',
    'dark:bg-[#1b2e4b]',
    'from-[#f09819]',
    'to-[#ff5858]',

    // Layout
    'container',
    'flex',
    'flex-col',
    'flex-row',
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'hidden',
    'block',
    'inline-block',
    'inline',
    'table',
    'table-row',
    'table-cell',

    // Flexbox & Grid
    'justify-start',
    'justify-end',
    'justify-center',
    'justify-between',
    'justify-around',
    'items-start',
    'items-end',
    'items-center',
    'items-baseline',
    'items-stretch',
    'gap-1',
    'gap-2',
    'gap-4',
    'gap-6',
    'gap-8',

    // Spacing
    'm-1',
    'm-2',
    'm-4',
    'm-8',
    'mx-auto',
    'p-1',
    'p-2',
    'p-4',
    'p-8',

    // Sizing
    'w-full',
    'w-auto',
    'h-full',
    'h-auto',

    // Typography
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'font-light',
    'font-normal',
    'font-medium',
    'font-semibold',
    'font-bold',
    'text-left',
    'text-center',
    'text-right',
    'text-gray-500',
    'text-gray-700',
    'text-gray-900',

    // Backgrounds
    'bg-white',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-300',
    'bg-gray-400',
    'bg-gray-500',
    'bg-red-500',
    'bg-blue-500',
    'bg-green-500',
    'bg-yellow-500',
    'bg-opacity-25',
    'bg-opacity-50',
    'bg-opacity-75',

    // Gradients
    'bg-gradient-to-r',
    'bg-gradient-to-l',
    'bg-gradient-to-t',
    'bg-gradient-to-b',
    'from-cyan-500',
    'to-cyan-400',
    'from-blue-500',
    'to-blue-400',
    'from-red-500',
    'to-red-400',
    'from-green-500',
    'to-green-400',

    // Borders
    'border',
    'border-0',
    'border-2',
    'border-4',
    'border-8',
    'border-gray-200',
    'border-gray-300',
    'border-gray-400',
    'rounded',
    'rounded-md',
    'rounded-lg',
    'rounded-full',

    // Effects
    'shadow',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
    'opacity-25',
    'opacity-50',
    'opacity-75',

    // Transitions & Animation
    'transition',
    'duration-300',
    'ease-in-out',

    // Interactivity
    'cursor-pointer',
    'select-none',

    // SVG
    'fill-current',
    'stroke-current',

    // Accessibility
    'sr-only',

    // Custom classes
    'panel',

    // Add any other specific classes you're using dynamically
  ],

  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        primary: {
          DEFAULT: '#4361ee',
          light: '#eaf1ff',
          'dark-light': 'rgba(67,97,238,.15)',
        },
        secondary: {
          DEFAULT: '#805dca',
          light: '#ebe4f7',
          'dark-light': 'rgb(128 93 202 / 15%)',
        },
        success: {
          DEFAULT: '#00ab55',
          light: '#ddf5f0',
          'dark-light': 'rgba(0,171,85,.15)',
        },
        danger: {
          DEFAULT: '#e7515a',
          light: '#fff5f5',
          'dark-light': 'rgba(231,81,90,.15)',
        },
        warning: {
          DEFAULT: '#e2a03f',
          light: '#fff9ed',
          'dark-light': 'rgba(226,160,63,.15)',
        },
        info: {
          DEFAULT: '#2196f3',
          light: '#e7f7ff',
          'dark-light': 'rgba(33,150,243,.15)',
        },
        dark: {
          DEFAULT: '#3b3f5c',
          light: '#eaeaec',
          'dark-light': 'rgba(59,63,92,.15)',
        },
        black: {
          DEFAULT: '#0e1726',
          light: '#e3e4eb',
          'dark-light': 'rgba(14,23,38,.15)',
        },
        white: {
          DEFAULT: '#ffffff',
          light: '#e0e6ed',
          dark: '#888ea8',
        },
      },
      fontFamily: {
        nunito: ['Nunito', 'sans-serif'],
      },
      spacing: {
        4.5: '18px',
      },
      boxShadow: {
        '3xl': '0 2px 2px rgb(224 230 237 / 46%), 1px 6px 7px rgb(224 230 237 / 46%)',
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            '--tw-prose-invert-headings': theme('colors.white.dark'),
            '--tw-prose-invert-links': theme('colors.white.dark'),
            h1: {
              fontSize: '40px',
              marginBottom: '0.5rem',
              marginTop: 0,
            },
            h2: {
              fontSize: '32px',
              marginBottom: '0.5rem',
              marginTop: 0,
            },
            h3: {
              fontSize: '28px',
              marginBottom: '0.5rem',
              marginTop: 0,
            },
            h4: {
              fontSize: '24px',
              marginBottom: '0.5rem',
              marginTop: 0,
            },
            h5: {
              fontSize: '20px',
              marginBottom: '0.5rem',
              marginTop: 0,
            },
            h6: {
              fontSize: '16px',
              marginBottom: '0.5rem',
              marginTop: 0,
            },
            p: { marginBottom: '0.5rem' },
            li: { margin: 0 },
            img: { margin: 0 },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/forms')({
      strategy: 'class',
    }),
    require('@tailwindcss/typography'),
  ],
};
