export const commonConfig: any = {
  API: {
    login: 'auth/admin/login',
    logout: 'auth/logout',
    getallprofile: 'auth/profile',
    updateprofile: 'auth/profile',
    updateprofileimage: 'auth/profile/picture',
    configpicture: 'auth/config/picture',
    excelUpdate: 'auth/export/file',
    getExcelHeaders: 'auth/export/get-excel-headers',
    updateprofilepwd: 'auth/password/change',
    resetuserpwd: 'auth/password/reset-pwd-user',
    commongriddata: 'common/grid-data',
    commonindividualdataexport: 'common/individual-data-export',
    commongriddataexport: 'common/grid-data-export',
    forgetpasswordEmail: 'auth/admin/password/request/',
    resetpasswordEmail: 'auth/admin/password/reset',
    commonlistdata: 'common/list-data',
    importtemplatedetails: 'common/import-template/details',
    importtemplatevalidate: 'common/import-template/validate/',
    commonexecutetransaction: 'common/execute-transaction',
    getAllMenu: 'user/menus',
    getCommnList: 'common/list-data',
    postCommnList: 'common/execute-transaction',
    listdata: 'common/list-data',
    executeRecords: 'common/execute-transaction',
    executeRecordsCase: 'common/execute-transaction-case',

    getTablesList: 'common/tables',
    procedureCall: 'common/procedure/',
    unauthprocedureCall: 'common/call-procedure/',
    uploadImageAndGetName: 'common/file-upload/image',
    deleteImageByName: 'common/file-delete/image',
    getLanguageContent: 'common/language-content',
    importtemplatedeletefile: 'common/import-template/remove',
    importtemplateuploaddata: 'common/import-template/upload',
    attachedpolicies: 'common/attached-policies',
    generatePowerBiEmbedToken: 'auth/powerbi/report/generate-embed-token',
    create_cron_jobs: 'common/create-cron-jobs',
    get_cron_jobs: 'common/get-cron-jobs',
    stop_cron_jobs: 'common/stop-cron-jobs',
    stop_cron_job: 'common/stop-cron-job',
    start_cron_job: 'common/start-cron-job',
    restart_cron_jobs: 'common/restart-cron-jobs',
    edit_cron_job: 'common/edit-cron-job',
    delete_cron_jobs: 'common/delete-cron-job',

    syncTableSchema: 'openai/generate-schema-chunks',
    generateVector: 'openai/generate-vector',
    generateAiQuery: 'openai/generate-query',
    getResultFromQuery: 'openai/get-response-from-sql',
    generateVectorForTable: 'openai/generate-vector-for-table',
  },
  ENTITY_TYPES: {
    GRID_BUILDER_MODULE: 'grid_builder_module',
    FORM_BUILDER_MODULE: 'form_builder_module',
    STATIC_PAGE_BUILDER_MODULE: 'static_page_builder_module',
    JOB_BUILDER_MODULE: 'job_builder_module',
    DASHBOARD_WIZARD_BUILDER_MODULE: 'dashboard_wizard_builder_module',
    ENTITY_USER_ROLE_MAP_MODULE: 'entity_user_role_map_module',
    USER_ROLE_PERMISSION_MAP_MODULE: 'user_role_permission_map_module',
    MENU_MODULE: 'menu_module',
    IMPORT_MODULE: 'import_module',
    EXPORT_MODULE: 'export_module',
    ENTITY_FORM_MODULE: 'entity_form_module',
    LANGUAGE_CONTENTS_MODULE: 'language_contents_module',
    CONFIGURATIONS_MODULE: 'configurations_module',
    CRON_SETTING_MODULE: 'cron_setting_module',
    IMPORT_TEMPLATE_MODULE: 'import_template_module',
    EXPORT_TEMPLATE_MODULE: 'export_template_module',
    IMPORT_JOB_DETAIL_MODULE: 'import_job_detail_module',
    POLICY_ADD_EDIT_MODULE: 'policy_add_edit_module',
    USER_ROLE_POLICY_MODULE: 'user_role_policy_module',
    EMAIL_TEMPLATE_ASSIGNMENT_MODULE: 'email_template_assignment_module',
    APPROVAL_WORKFLOW_ASSIGNMENT_MODULE: 'approval_workflow_assignment_module',
    APPROVAL_REQUESTS_MODULE: 'approval_requests_module',
    APPROVAL_REQUESTS_TRACKING_MODULE: 'approval_requests_tracking_module',
    ABOUT_LCP_FORM_MODULE: 'about_lcp_form_module',
    AI_PLAYGROUND_MODULE: 'ai_playground_module',
  },
  PREFIX_SHORTCODE: {
    grid_builder_module: 'grid',
    form_builder_module: 'form',
    static_page_builder_module: 'staticpage',
    job_builder_module: 'job',
    dashboard_wizard_builder_module: 'dashboard',
    entity_user_role_map_module: 'userroleperm',
    user_role_permission_map_module: 'userroleperm',
    menu_module: 'menu',
    import_module: 'import',
    export_module: 'export',
    entity_form_module: 'entityform',
    language_contents_module: 'lang',
    configurations_module: 'config',
    cron_setting_module: 'cronsetting',
    import_template_module: 'importtemplate',
    export_template_module: 'exporttemplate',
    import_job_detail_module: 'importjobdetail',
    policy_add_edit_module: 'policyaddedit',
    user_role_policy_module: 'userrolepolicy',
    email_template_assignment_module: 'emailtemplateassignment',
    approval_workflow_assignment_module: 'approvalworkflowassignment',
    approval_requests_module: 'approvalrequests',
    approval_requests_tracking_module: 'approvalrequeststracking',
    about_lcp_form_module: 'aboutlcpformmodule',
    ai_playground_module: 'aiplayground',
  },
  MENU_LINK_TYPE: {
    GENERAL: 1,
    ACTION: 2,
    ACTION_AND_GENERAL: 3,
    EXTERNAL: 4,
  },
  menu_link_type: [
    { label: 'General', value: 1 },
    { label: 'Action', value: 2 },
    { label: 'Action AND General', value: 3 },
    { label: 'External', value: 4 },
  ],
  menu_device_type: [
    { label: 'Web', value: 1 },
    { label: 'Mobile', value: 2 },
  ],
  STATUS: {
    ACTIVE: 1,
    INACTIVE: 2,
    DELETED: 3,
  },
  ACTION_TYPE: {
    VIEW: 'view',
    ADD: 'add',
    EDIT: 'edit',
    DELETE: 'delete',
    VIEW_DETAILS: 'details',
    EXPORT_AS_EXCEL: 'export_excel',
    IMPORT: 'import',
    ASSIGN: 'assign',
    Print: 'print',
    RECORD_EXPORT: 'record_export',
    EMAIL_RESEND: 'email_resend',
    GENERATE_VECTOR: 'generate_vector',
  },
  status_type: [
    { label: 'Active', value: 1 },
    { label: 'InActive', value: 2 },
  ],
  field_types: [
    { label: 'field_types_integer', value: 1 },
    { label: 'field_types_float', value: 2 },
    { label: 'field_types_string', value: 3 },
    { label: 'field_types_big_string', value: 4 },
    { label: 'field_types_date', value: 5 },
    { label: 'field_types_time', value: 6 },
    { label: 'field_types_date_time', value: 7 },
    { label: 'field_types_integer_range', value: 8 },
    { label: 'field_types_float_range', value: 9 },
    { label: 'field_types_date_range', value: 10 },
    { label: 'field_types_json', value: 11 },
  ],
  action_types: [
    { label: 'View', value: 'view' },
    { label: 'Add', value: 'add' },
    { label: 'Edit', value: 'edit' },
    { label: 'Delete', value: 'delete' },
    { label: 'Details', value: 'details' },
    { label: 'Export As Excel', value: 'export_excel' },
    { label: 'Import', value: 'import' },
    { label: 'Assign', value: 'assign' },
    { label: 'Print', value: 'print' },
    { label: 'Record Export', value: 'record_export' },
    { label: 'Resend Email', value: 'email_resend' },
    { label: 'Generate Vector', value: 'generate_vector' },
  ],
  entity_types: [
    { label: 'Grid Builder Module', value: 'grid_builder_module' },
    { label: 'Form Builder Module', value: 'form_builder_module' },
    { label: 'Page Builder Module', value: 'static_page_builder_module' },
    { label: 'Job Builder Module', value: 'job_builder_module' },
    { label: 'Dashboard Wizard Builder Module', value: 'dashboard_wizard_builder_module' },
    { label: 'Entity User/Role Mapping Module', value: 'entity_user_role_map_module' },
    { label: 'User/Role Permission Mapping Module', value: 'user_role_permission_map_module' },
    { label: 'Menu Module', value: 'menu_module' },
    { label: 'Import Module', value: 'import_module' },
    { label: 'Export Module', value: 'export_module' },
    { label: 'Entity Add/Edit Module', value: 'entity_form_module' },
    { label: 'Language Contents Module', value: 'language_contents_module' },
    { label: 'Configurations Module', value: 'configurations_module' },
    { label: 'Cron Setting Module', value: 'cron_setting_module' },
    { label: 'Import Template Module', value: 'import_template_module' },
    { label: 'Import Job Detail Module', value: 'import_job_detail_module' },

    { label: 'Export Template Module', value: 'export_template_module' },
    { label: 'Policy Add Edit Module', value: 'policy_add_edit_module' },
    { label: 'User/Role Policy Module', value: 'user_role_policy_module' },
    { label: 'Email Template Assignment Module', value: 'email_template_assignment_module' },
    { label: 'Approval Workflow Assignment Module', value: 'approval_workflow_assignment_module' },
    { label: 'Approval Requests Module', value: 'approval_requests_module' },
    { label: 'Approval Requests Tracking Module', value: 'approval_requests_tracking_module' },
    { label: 'About Lcp Form Module', value: 'about_lcp_form_module' },
    { label: 'AI Playground Module', value: 'ai_playground_module' },
  ],
  keypress_config: {
    allow_only_lowercase_alphanumeric: 'allow_only_lowercase_alphanumeric',
  },
  common_search_conditions: [
    { id: '1', label: 'Equals', value: '=' },
    { id: '2', label: 'Not Equals', value: '!=' },
    { id: '3', label: 'Greater Than', value: '>' },
    { id: '4', label: 'Greater Than or Equal To', value: '>=' },
    { id: '5', label: 'Less Than', value: '<' },
    { id: '6', label: 'Less Than or Equal To', value: '<=' },
    { id: '7', label: 'Contains', value: 'contains' },
    { id: '8', label: 'Does Not Contain', value: 'not_contains' },
    { id: '9', label: 'Starts With', value: 'starts_with' },
    { id: '10', label: 'Ends With', value: 'ends_with' },
    { id: '11', label: 'Is Empty', value: 'is_empty' },
    { id: '12', label: 'Is Not Empty', value: 'is_not_empty' },
    { id: '13', label: 'Is Null', value: 'is_null' },
    { id: '14', label: 'Is Not Null', value: 'is_not_null' },
  ],
  search_conditions: {
    // Integer Field Conditions
    1: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Greater Than', value: '>' },
      { id: '4', label: 'Greater Than or Equal To', value: '>=' },
      { id: '5', label: 'Less Than', value: '<' },
      { id: '6', label: 'Less Than or Equal To', value: '<=' },
      { id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // Float Field Conditions
    2: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Greater Than', value: '>' },
      { id: '4', label: 'Greater Than or Equal To', value: '>=' },
      { id: '5', label: 'Less Than', value: '<' },
      { id: '6', label: 'Less Than or Equal To', value: '<=' },
      { id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // String Field Conditions
    3: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Contains', value: 'contains' },
      { id: '4', label: 'Does Not Contain', value: 'not_contains' },
      { id: '5', label: 'Starts With', value: 'starts_with' },
      { id: '6', label: 'Ends With', value: 'ends_with' },
      { id: '7', label: 'Is Empty', value: 'is_empty' },
      { id: '8', label: 'Is Not Empty', value: 'is_not_empty' },
      { id: '9', label: 'Is Null', value: 'is_null' },
      { id: '10', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // Big String Field Conditions
    4: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Contains', value: 'contains' },
      { id: '4', label: 'Does Not Contain', value: 'not_contains' },
      { id: '5', label: 'Starts With', value: 'starts_with' },
      { id: '6', label: 'Ends With', value: 'ends_with' },
      { id: '7', label: 'Is Empty', value: 'is_empty' },
      { id: '8', label: 'Is Not Empty', value: 'is_not_empty' },
      { id: '9', label: 'Is Null', value: 'is_null' },
      { id: '10', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // Date Field Conditions
    5: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Before', value: '<' },
      { id: '4', label: 'On or Before', value: '<=' },
      { id: '5', label: 'After', value: '>' },
      { id: '6', label: 'On or After', value: '>=' },
      /*{ id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },*/
    ],

    // DateTime Field Conditions
    6: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Before', value: '<' },
      { id: '4', label: 'On or Before', value: '<=' },
      { id: '5', label: 'After', value: '>' },
      { id: '6', label: 'On or After', value: '>=' },
      /*{ id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },*/
    ],

    // DateTime Field Conditions
    7: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Before', value: '<' },
      { id: '4', label: 'On or Before', value: '<=' },
      { id: '5', label: 'After', value: '>' },
      { id: '6', label: 'On or After', value: '>=' },
      /*{ id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },*/
    ],

    // Integer Range Field Conditions
    8: [
      { id: '1', label: 'Between', value: 'between' },
      { id: '2', label: 'Not Between', value: 'not_between' },
      { id: '3', label: 'Is Null', value: 'is_null' },
      { id: '4', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // Float Range Field Conditions
    9: [
      { id: '1', label: 'Between', value: 'between' },
      { id: '2', label: 'Not Between', value: 'not_between' },
      { id: '3', label: 'Is Null', value: 'is_null' },
      { id: '4', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // Date Range Field Conditions
    10: [
      { id: '1', label: 'Between', value: 'between' },
      { id: '2', label: 'Not Between', value: 'not_between' },
      { id: '3', label: 'Is Null', value: 'is_null' },
      { id: '4', label: 'Is Not Null', value: 'is_not_null' },
    ],
  },
  field_type: {
    1: 'number',
    2: 'number',
    3: 'text',
    4: 'text',
    5: 'date',
    6: 'datetime-local',
    7: 'datetime-local',
    8: 'number',
    9: 'number',
    10: 'date',
    11: 'json',
  },
  wizard_type: [
    {
      label: 'Chart',
      value: 'chart',
    },
    {
      label: 'Static',
      value: 'static',
    },
  ],
  WIZARD_TYPES: {
    CHART: 'chart',
    STATIC: 'static',
  },
  report_type: [
    {
      label: 'LCP',
      value: 'lcp',
    },
    {
      label: 'Power Bi',
      value: 'powerbi',
    },
  ],
  REPORT_TYPES: {
    LCP: 'lcp',
    POWERBI: 'powerbi',
  },
};
