export const commonConfig: any = {
  API: {
    processImportJob: 'common/process-import-job',
    login: 'auth/admin/login',
    switchCompany: 'auth/switch-company',
    switchCompanies: 'auth/companies',
    logout: 'auth/logout',
    getallprofile: 'auth/profile',
    updateprofile: 'auth/profile',
    updateprofileimage: 'auth/profile/picture',
    configpicture: 'auth/config/picture',
    excelUpdate: 'auth/export/file',
    getExcelHeaders: 'auth/export/get-excel-headers',
    updateprofilepwd: 'auth/password/change',
    resetuserpwd: 'auth/password/reset-pwd-user',
    commongriddata: 'common/grid-data',
    commonindividualdataexportalone: 'common/individual-data-export-alone',
    commonindividualdataexport: 'common/individual-data-export',
    commongriddataexport: 'common/grid-data-export',
    forgetpasswordEmail: 'auth/admin/password/request/',
    resetpasswordEmail: 'auth/admin/password/reset',
    commonlistdata: 'common/list-data',
    unauthcommonlistdata: 'common/unauth-list-data',
    importtemplatedetails: 'common/import-template/details',
    importtemplatevalidate: 'common/import-template/validate/',
    importtemplatevalidatescheduled: 'common/import-template/validate-scheduled/',
    commonexecutetransaction: 'common/execute-transaction',
    getAllMenu: 'user/menus',
    getCommnList: 'common/list-data',
    getCommnListConfiguration: 'common/list-data-configuration-alone',
    postCommnList: 'common/execute-transaction',
    listdata: 'common/list-data',
    listdataconfig: 'common/list-data-configuration',
    tenantRegistrationLovValues: 'tenant-registration/lov-values',
    tenantRegistrationCheckEmail: 'tenant-registration/check-email',
    tenantRegistrationRegister: 'tenant-registration/register',
    tenantRegistrationAddCompany: 'tenant-registration/add-company',
    tenantRegistrationList: 'tenant-registration/list',
    tenantRegistrationSummary: 'tenant-registration',
    tenantRegistrationApprove: 'tenant-registration',
    tenantRegistrationReject: 'tenant-registration',
    executeRecords: 'common/execute-transaction',
    executeRecordsCase: 'common/execute-transaction-case',
    executeRecordsConfig: 'common/execute-transaction-configuration',
    entitydetails: 'common/entity-name',

    getTablesList: 'common/tables',
    procedureCall: 'common/procedure/',
    unauthprocedureCall: 'common/call-procedure/',
    uploadImageAndGetName: 'common/file-upload/image',
    deleteImageByName: 'common/file-delete/image',
    getLanguageContent: 'common/language-content',
    getThemeInfo: 'common/theme-info',
    importtemplatedeletefile: 'common/import-template/remove',
    importtemplateuploaddata: 'common/import-template/upload',
    attachedpolicies: 'common/attached-policies',
    generatePowerBiEmbedToken: 'auth/powerbi/report/generate-embed-token',
    create_cron_jobs: 'common/create-cron-jobs',
    get_cron_jobs: 'common/get-cron-jobs',
    stop_cron_jobs: 'common/stop-cron-jobs',
    stop_cron_job: 'common/stop-cron-job',
    start_cron_job: 'common/start-cron-job',
    restart_cron_jobs: 'common/restart-cron-jobs',
    edit_cron_job: 'common/edit-cron-job',
    delete_cron_jobs: 'common/delete-cron-job',

    migrate_entity_export: 'migrate/export-entity',
    migrate_entity_import: 'migrate/import-entity',
    migrate_master_entity: 'migrate/master-entity',

    syncTableSchema: 'openai/generate-schema-chunks',
    generateVector: 'openai/generate-vector',
    generateAiQuery: 'openai/generate-query',
    getResultFromQuery: 'openai/get-response-from-sql',
    generateVectorForTable: 'openai/generate-vector-for-table',
    generateAiContent: 'openai/generate-query-json',
    execute_child_process: 'common/execute-child-process',
    transcribe_audio: 'openai/transcribe-audio',
    search_menu_target_embeddings: 'openai/search-menu-target-embeddings',
    generate_menu_embeddings: 'openai/generate-menu-embeddings',
  },
  ENTITY_TYPES: {
    GRID_BUILDER_MODULE: { name: 'grid_builder_module', prefix_slug: 'grid' },
    FORM_BUILDER_MODULE: { name: 'form_builder_module', prefix_slug: 'form' },
    STATIC_PAGE_BUILDER_MODULE: { name: 'static_page_builder_module', prefix_slug: 'staticpage' },
    JOB_BUILDER_MODULE: { name: 'job_builder_module', prefix_slug: 'job' },
    DASHBOARD_WIZARD_BUILDER_MODULE: { name: 'dashboard_wizard_builder_module', prefix_slug: 'dashboard' },
    ENTITY_USER_ROLE_MAP_MODULE: { name: 'entity_user_role_map_module', prefix_slug: 'userroleperm' },
    USER_ROLE_PERMISSION_MAP_MODULE: { name: 'user_role_permission_map_module', prefix_slug: 'userroleperm' },
    MENU_MODULE: { name: 'menu_module', prefix_slug: 'menu' },
    IMPORT_MODULE: { name: 'import_module', prefix_slug: 'import' },
    MIGRATION_MODULE: { name: 'migrate_entity', prefix_slug: 'migrate' },
    EXPORT_MODULE: { name: 'export_module', prefix_slug: 'export' },
    ENTITY_FORM_MODULE: { name: 'entity_form_module', prefix_slug: 'entityform' },
    LANGUAGE_CONTENTS_MODULE: { name: 'language_contents_module', prefix_slug: 'lang' },
    BARCODE_PRINT_MODULE: { name: 'barcode_print_module', prefix_slug: 'barcode' },
    CONFIGURATIONS_MODULE: { name: 'configurations_module', prefix_slug: 'config' },
    USER_CONFIGURATIONS_MODULE: { name: 'user_configurations_module', prefix_slug: 'userconfig' },
    CRON_SETTING_MODULE: { name: 'cron_setting_module', prefix_slug: 'cronsetting' },
    IMPORT_TEMPLATE_MODULE: { name: 'import_template_module', prefix_slug: 'importtemplate' },
    EXPORT_TEMPLATE_MODULE: { name: 'export_template_module', prefix_slug: 'exporttemplate' },
    IMPORT_JOB_DETAIL_MODULE: { name: 'import_job_detail_module', prefix_slug: 'importjobdetail' },
    POLICY_ADD_EDIT_MODULE: { name: 'policy_add_edit_module', prefix_slug: 'policyaddedit' },
    USER_ROLE_POLICY_MODULE: { name: 'user_role_policy_module', prefix_slug: 'userrolepolicy' },
    EMAIL_TEMPLATE_ASSIGNMENT_MODULE: { name: 'email_template_assignment_module', prefix_slug: 'emailtemplateassignment' },
    WHATSAPP_TEMPLATE_ASSIGNMENT_MODULE: { name: 'whatsapp_template_assignment_module', prefix_slug: 'whatsapptemplateassignment' },
    APPROVAL_WORKFLOW_ASSIGNMENT_MODULE: { name: 'approval_workflow_assignment_module', prefix_slug: 'approvalworkflowassignment' },
    APPROVAL_REQUESTS_MODULE: { name: 'approval_requests_module', prefix_slug: 'approvalrequests' },
    APPROVAL_REQUESTS_TRACKING_MODULE: { name: 'approval_requests_tracking_module', prefix_slug: 'approvalrequeststracking' },
    ABOUT_LCP_FORM_MODULE: { name: 'about_lcp_form_module', prefix_slug: 'aboutlcpformmodule' },
    AI_PLAYGROUND_MODULE: { name: 'ai_playground_module', prefix_slug: 'aiplayground' },
    CHILD_PROCESS_SETTING_MODULE: { name: 'child_process_setting_module', prefix_slug: 'childprocesssetting' },
    QUERY_BUILDER_MODULE: { name: 'query_builder_module', prefix_slug: 'querybuilder' },
    CAROUSEL_MODULE: { name: 'carousel_module', prefix_slug: 'carouselmodule' },
    COMMON_PERMISSION_MODULE: { name: 'common_permission_module', prefix_slug: 'commonpermissionmodule' },
    TREE_BUILDER_MODULE: { name: 'tree_builder_module', prefix_slug: 'treebuildermodule' },
    TARGET_KEYWORDS_EMBEDDINGS_MODULE: { name: 'target_keywords_embeddings_module', prefix_slug: 'targetkeywordsembeddingsmodule' },
    AUDIT_LOG_MANAGEMENT_MODULE: { name: 'audit_log_management_module', prefix_slug: 'auditlogmanagement' },
    CHART_BUILDER_MODULE: { name: 'chart_builder_module', prefix_slug: 'chartbuilder' },
    USER_COMPANY_MAP_MODULE: { name: 'user_company_map_module', prefix_slug: 'usercompany' },
    APPROVAL_WORKFLOW_BUILDER_MODULE: { name: 'approval_workflow_builder_module', prefix_slug: 'approvalworkflowbuilder' },
    APPROVAL_WORKFLOW: { name: 'approval_workflow', prefix_slug: 'approvalworkflow' },
    TENANTS: { name: 'tenant_module', prefix_slug: 'tenants' },
  },
  MENU_LINK_TYPE: {
    GENERAL: 1,
    ACTION: 2,
    ACTION_AND_GENERAL: 3,
    EXTERNAL: 4,
    HIDDEN: 5,
  },
  menu_link_type: [
    { label: 'General', value: 1 },
    { label: 'Action', value: 2 },
    { label: 'Action AND General', value: 3 },
    { label: 'External', value: 4 },
    { label: 'Hidden', value: 5 },
  ],
  menu_device_type: [
    { label: 'Web', value: 1 },
    { label: 'Mobile', value: 2 },
  ],
  STATUS: {
    ACTIVE: 1,
    INACTIVE: 2,
    DELETED: 3,
  },
  ACTION_TYPE: {
    VIEW: 'view',
    ADD: 'add',
    EDIT: 'edit',
    DELETE: 'delete',
    VIEW_DETAILS: 'details',
    EXPORT_AS_EXCEL: 'export_excel',
    EXPORT_AS_PDF: 'export_pdf',
    IMPORT: 'import',
    ASSIGN: 'assign',
    Print: 'print',
    RECORD_EXPORT: 'record_export',
    EMAIL_RESEND: 'email_resend',
    GENERATE_VECTOR: 'generate_vector',
    CHILD_DETAILS: 'child_details',
    POPUP_ADD: 'popup_add',
    POPUP_EDIT: 'popup_edit',
    POPUP_DETAILS: 'popup_details',
    RESET_PASSWORD: 'reset_password',
    GET_CODE: 'get_code',
  },
  status_type: [
    { label: 'Active', value: 1 },
    { label: 'InActive', value: 2 },
  ],
  field_types: [
    { label: 'field_types_integer', value: 1 },
    { label: 'field_types_float', value: 2 },
    { label: 'field_types_string', value: 3 },
    { label: 'field_types_big_string', value: 4 },
    { label: 'field_types_date', value: 5 },
    { label: 'field_types_time', value: 6 },
    { label: 'field_types_date_time', value: 7 },
    { label: 'field_types_integer_range', value: 8 },
    { label: 'field_types_float_range', value: 9 },
    { label: 'field_types_date_range', value: 10 },
    { label: 'field_types_json', value: 11 },
  ],
  action_types: [
    { label: 'View', value: 'view' },
    { label: 'Add', value: 'add' },
    { label: 'Edit', value: 'edit' },
    { label: 'Delete', value: 'delete' },
    { label: 'Details', value: 'details' },
    { label: 'Export As Excel', value: 'export_excel' },
    { label: 'Export As PDF', value: 'export_pdf' },
    { label: 'Import', value: 'import' },
    { label: 'Assign', value: 'assign' },
    { label: 'Print', value: 'print' },
    { label: 'Record Export', value: 'record_export' },
    { label: 'Resend Email', value: 'email_resend' },
    { label: 'Generate Vector', value: 'generate_vector' },
    { label: 'Child Details', value: 'child_details' },

    { label: 'Popup Add', value: 'popup_add' },
    { label: 'Popup Edit', value: 'popup_edit' },
    { label: 'Popup Details', value: 'popup_details' },
    { label: 'Reset Password', value: 'reset_password' },
    { label: 'Get Code', value: 'get_code' },
  ],
  entity_types: [
    { label: 'Grid Builder Module', value: 'grid_builder_module' },
    { label: 'Form Builder Module', value: 'form_builder_module' },
    { label: 'Page Builder Module', value: 'static_page_builder_module' },
    { label: 'Job Builder Module', value: 'job_builder_module' },
    { label: 'Dashboard Wizard Builder Module', value: 'dashboard_wizard_builder_module' },
    { label: 'Entity User/Role Mapping Module', value: 'entity_user_role_map_module' },
    { label: 'User Company Mapping Module', value: 'user_company_map_module' },
    { label: 'User/Role Permission Mapping Module', value: 'user_role_permission_map_module' },
    { label: 'Menu Module', value: 'menu_module' },
    { label: 'Migrate Module', value: 'migrate_entity' },
    { label: 'Import Module', value: 'import_module' },
    { label: 'Export Module', value: 'export_module' },
    { label: 'Entity Add/Edit Module', value: 'entity_form_module' },
    { label: 'Language Contents Module', value: 'language_contents_module' },
    { label: 'Configurations Module', value: 'configurations_module' },
    { label: 'Barcode Print Module', value: 'barcode_print_module' },
    { label: 'User Configurations Module', value: 'user_configurations_module' },

    { label: 'Cron Setting Module', value: 'cron_setting_module' },
    { label: 'Import Template Module', value: 'import_template_module' },
    { label: 'Import Job Detail Module', value: 'import_job_detail_module' },

    { label: 'Export Template Module', value: 'export_template_module' },
    { label: 'Policy Add Edit Module', value: 'policy_add_edit_module' },
    { label: 'User/Role Policy Module', value: 'user_role_policy_module' },
    { label: 'Email Template Assignment Module', value: 'email_template_assignment_module' },
    { label: 'Approval Workflow Assignment Module', value: 'approval_workflow_assignment_module' },
    { label: 'Approval Requests Module', value: 'approval_requests_module' },
    { label: 'Approval Requests Tracking Module', value: 'approval_requests_tracking_module' },
    { label: 'About Lcp Form Module', value: 'about_lcp_form_module' },
    { label: 'AI Playground Module', value: 'ai_playground_module' },
    { label: 'Child Process Setting Module', value: 'child_process_setting_module' },
    { label: 'Query Builder Module', value: 'query_builder_module' },
    { label: 'Carousel Module', value: 'carousel_module' },
    { label: 'Common Permission Module', value: 'common_permission_module' },
    { label: 'Tree Builder Module', value: 'tree_builder_module' },
    { label: 'Target Keywords Embeddings Module', value: 'target_keywords_embeddings_module' },
    { label: 'Audit Log Management Module', value: 'audit_log_management_module' },
    { label: 'Chart Builder Module', value: 'chart_builder_module' },
    { label: 'Approval Workflow Builder Module', value: 'approval_workflow_builder_module' },
    { label: 'Approval Workflow', value: 'approval_workflow' },
    { label: 'Tenants Module', value: 'tenant_module' },
  ],
  keypress_config: {
    allow_only_lowercase_alphanumeric: 'allow_only_lowercase_alphanumeric',
  },
  common_search_conditions: [
    { id: '1', label: 'Equals', value: '=' },
    { id: '2', label: 'Not Equals', value: '!=' },
    { id: '3', label: 'Greater Than', value: '>' },
    { id: '4', label: 'Greater Than or Equal To', value: '>=' },
    { id: '5', label: 'Less Than', value: '<' },
    { id: '6', label: 'Less Than or Equal To', value: '<=' },
    { id: '7', label: 'Contains', value: 'contains' },
    { id: '8', label: 'Does Not Contain', value: 'not_contains' },
    { id: '9', label: 'Starts With', value: 'starts_with' },
    { id: '10', label: 'Ends With', value: 'ends_with' },
    { id: '11', label: 'Is Empty', value: 'is_empty' },
    { id: '12', label: 'Is Not Empty', value: 'is_not_empty' },
    { id: '13', label: 'Is Null', value: 'is_null' },
    { id: '14', label: 'Is Not Null', value: 'is_not_null' },
    { id: '15', label: 'IN', value: 'in' },
    { id: '16', label: 'NOT IN', value: 'not_in' },
  ],
  search_conditions: {
    // Integer Field Conditions
    1: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Greater Than', value: '>' },
      { id: '4', label: 'Greater Than or Equal To', value: '>=' },
      { id: '5', label: 'Less Than', value: '<' },
      { id: '6', label: 'Less Than or Equal To', value: '<=' },
      { id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },
      { id: '9', label: 'IN', value: 'in' },
      { id: '10', label: 'NOT IN', value: 'not_in' },
    ],

    // Float Field Conditions
    2: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Greater Than', value: '>' },
      { id: '4', label: 'Greater Than or Equal To', value: '>=' },
      { id: '5', label: 'Less Than', value: '<' },
      { id: '6', label: 'Less Than or Equal To', value: '<=' },
      { id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },
      { id: '9', label: 'IN', value: 'in' },
      { id: '10', label: 'NOT IN', value: 'not_in' },
    ],

    // String Field Conditions
    3: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Contains', value: 'contains' },
      { id: '4', label: 'Does Not Contain', value: 'not_contains' },
      { id: '5', label: 'Starts With', value: 'starts_with' },
      { id: '6', label: 'Ends With', value: 'ends_with' },
      { id: '7', label: 'Is Empty', value: 'is_empty' },
      { id: '8', label: 'Is Not Empty', value: 'is_not_empty' },
      { id: '9', label: 'Is Null', value: 'is_null' },
      { id: '10', label: 'Is Not Null', value: 'is_not_null' },
      { id: '11', label: 'IN', value: 'in' },
      { id: '12', label: 'NOT IN', value: 'not_in' },
    ],

    // Big String Field Conditions
    4: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Contains', value: 'contains' },
      { id: '4', label: 'Does Not Contain', value: 'not_contains' },
      { id: '5', label: 'Starts With', value: 'starts_with' },
      { id: '6', label: 'Ends With', value: 'ends_with' },
      { id: '7', label: 'Is Empty', value: 'is_empty' },
      { id: '8', label: 'Is Not Empty', value: 'is_not_empty' },
      { id: '9', label: 'Is Null', value: 'is_null' },
      { id: '10', label: 'Is Not Null', value: 'is_not_null' },
      { id: '11', label: 'IN', value: 'in' },
      { id: '12', label: 'NOT IN', value: 'not_in' },
    ],

    // Date Field Conditions
    5: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Before', value: '<' },
      { id: '4', label: 'On or Before', value: '<=' },
      { id: '5', label: 'After', value: '>' },
      { id: '6', label: 'On or After', value: '>=' },
      { id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },
      { id: '9', label: 'IN', value: 'in' },
      { id: '10', label: 'NOT IN', value: 'not_in' },
    ],

    // DateTime Field Conditions
    6: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Before', value: '<' },
      { id: '4', label: 'On or Before', value: '<=' },
      { id: '5', label: 'After', value: '>' },
      { id: '6', label: 'On or After', value: '>=' },
      { id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // DateTime Field Conditions
    7: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Before', value: '<' },
      { id: '4', label: 'On or Before', value: '<=' },
      { id: '5', label: 'After', value: '>' },
      { id: '6', label: 'On or After', value: '>=' },
    ],

    // Integer Range Field Conditions
    8: [
      { id: '1', label: 'Between', value: 'between' },
      { id: '2', label: 'Not Between', value: 'not_between' },
      { id: '3', label: 'Is Null', value: 'is_null' },
      { id: '4', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // Float Range Field Conditions
    9: [
      { id: '1', label: 'Between', value: 'between' },
      { id: '2', label: 'Not Between', value: 'not_between' },
      { id: '3', label: 'Is Null', value: 'is_null' },
      { id: '4', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // Date Range Field Conditions
    10: [
      { id: '1', label: 'Between', value: 'between' },
      { id: '2', label: 'Not Between', value: 'not_between' },
      { id: '3', label: 'Is Null', value: 'is_null' },
      { id: '4', label: 'Is Not Null', value: 'is_not_null' },
    ],
  },
  field_type: {
    1: 'number',
    2: 'number',
    3: 'text',
    4: 'text',
    5: 'date',
    6: 'time',
    7: 'datetime-local',
    8: 'number',
    9: 'number',
    10: 'date',
    11: 'json',
  },
  wizard_type: [
    {
      label: 'Chart',
      value: 'chart',
    },
    {
      label: 'Static',
      value: 'static',
    },
    {
      label: 'Entity',
      value: 'entity',
    },
  ],
  WIZARD_TYPES: {
    CHART: 'chart',
    STATIC: 'static',
    ENTITY: 'entity',
  },
  report_type: [
    {
      label: 'LCP',
      value: 'lcp',
    },
    {
      label: 'Power Bi',
      value: 'powerbi',
    },
  ],
  REPORT_TYPES: {
    LCP: 'lcp',
    POWERBI: 'powerbi',
  },
};
