export const commonConfig = {
  API: {
    login: 'auth/admin/login',
    logout: 'auth/logout',
    getallprofile: 'auth/profile',
    updateprofile: 'auth/profile',
    updateprofileimage: 'auth/profile/picture',
    configpicture: 'auth/config/picture',
    updateprofilepwd: 'auth/password/change',
    commongriddata: 'common/grid-data',
    forgetpasswordEmail: 'auth/admin/password/request/',
    resetpasswordEmail: 'auth/admin/password/reset',
    commonlistdata: 'common/list-data',
    importtemplatedetails: 'common/import-template/details',
    importtemplatevalidate: 'common/import-template/validate/',
    commonexecutetransaction: 'common/execute-transaction',
    getAllMenu: 'user/menus',
    getCommnList: 'common/list-data',
    postCommnList: 'common/execute-transaction',
    listdata: 'common/list-data',
    executeRecords: 'common/execute-transaction',
    getTablesList: 'common/tables',
    procedureCall: 'common/procedure/',
    uploadImageAndGetName: 'common/file-upload/image',
    deleteImageByName: 'common/file-delete/image',
    getLanguageContent: 'common/language-content',
  },
  ENTITY_TYPES: {
    GRID_BUILDER_MODULE: 'grid_builder_module',
    FORM_BUILDER_MODULE: 'form_builder_module',
    STATIC_PAGE_BUILDER_MODULE: 'static_page_builder_module',
    JOB_BUILDER_MODULE: 'job_builder_module',
    DASHBOARD_WIZARD_BUILDER_MODULE: 'dashboard_wizard_builder_module',
    ENTITY_USER_ROLE_MAP_MODULE: 'entity_user_role_map_module',
    MENU_MODULE: 'menu_module',
    IMPORT_MODULE: 'import_module',
    ENTITY_FORM_MODULE: 'entity_form_module',
    LANGUAGE_CONTENTS_MODULE: 'language_contents_module',
    CONFIGURATIONS_MODULE: 'configurations_module',
  },
  MENU_LINK_TYPE: {
    GENERAL: 1,
    ACTION: 2,
    ACTION_AND_GENERAL: 3,
    EXTERNAL: 4,
  },
  menu_link_type: [
    { label: 'General', value: 1 },
    { label: 'Action', value: 2 },
    { label: 'Action AND General', value: 3 },
    { label: 'External', value: 4 },
  ],
  menu_device_type: [
    { label: 'Web', value: 1 },
    { label: 'Mobile', value: 2 },
  ],
  STATUS: {
    ACTIVE: 1,
    INACTIVE: 2,
    DELETED: 3,
  },
  ACTION_TYPE: {
    VIEW: 'view',
    ADD: 'add',
    EDIT: 'edit',
    DELETE: 'delete',
    VIEW_DETAILS: 'details',
    EXPORT: 'export',
    IMPORT: 'import',
    ASSIGN: 'assign',
  },
  status_type: [
    { label: 'Active', value: 1 },
    { label: 'InActive', value: 2 },
  ],
  field_types: [
    { label: 'field_types_integer', value: 1 },
    { label: 'field_types_float', value: 2 },
    { label: 'field_types_string', value: 3 },
    { label: 'field_types_big_string', value: 4 },
    { label: 'field_types_date', value: 5 },
    { label: 'field_types_time', value: 6 },
    { label: 'field_types_date_time', value: 7 },
    { label: 'field_types_integer_range', value: 8 },
    { label: 'field_types_float_range', value: 9 },
    { label: 'field_types_date_range', value: 10 },
  ],
  action_types: [
    { label: 'View', value: 'view' },
    { label: 'Add', value: 'add' },
    { label: 'Edit', value: 'edit' },
    { label: 'Delete', value: 'delete' },
    { label: 'Details', value: 'details' },
    { label: 'Export', value: 'export' },
    { label: 'Import', value: 'import' },
    { label: 'Assign', value: 'assign' },
  ],
  entity_types: [
    { label: 'Grid Builder Module', value: 'grid_builder_module' },
    { label: 'Form Builder Module', value: 'form_builder_module' },
    { label: 'Page Builder Module', value: 'static_page_builder_module' },
    { label: 'Job Builder Module', value: 'job_builder_module' },
    { label: 'Dashboard Wizard Builder Module', value: 'dashboard_wizard_builder_module' },
    { label: 'Entity User/Role Mapping Module', value: 'entity_user_role_map_module' },
    { label: 'Menu Module', value: 'menu_module' },
    { label: 'Import Module', value: 'import_module' },
    { label: 'Entity Add/Edit Module', value: 'entity_form_module' },
    { label: 'Language Contents Module', value: 'language_contents_module' },
    { label: 'Configurations Module', value: 'configurations_module' },
  ],
  keypress_config: {
    allow_only_lowercase_alphanumeric: 'allow_only_lowercase_alphanumeric',
  },
  common_search_conditions: [
    { id: '1', label: 'Equals', value: '=' },
    { id: '2', label: 'Not Equals', value: '!=' },
    { id: '3', label: 'Greater Than', value: '>' },
    { id: '4', label: 'Greater Than or Equal To', value: '>=' },
    { id: '5', label: 'Less Than', value: '<' },
    { id: '6', label: 'Less Than or Equal To', value: '<=' },
    { id: '7', label: 'Contains', value: 'contains' },
    { id: '8', label: 'Does Not Contain', value: 'not_contains' },
    { id: '9', label: 'Starts With', value: 'starts_with' },
    { id: '10', label: 'Ends With', value: 'ends_with' },
    { id: '11', label: 'Is Empty', value: 'is_empty' },
    { id: '12', label: 'Is Not Empty', value: 'is_not_empty' },
    { id: '13', label: 'Is Null', value: 'is_null' },
    { id: '14', label: 'Is Not Null', value: 'is_not_null' },
  ],
  search_conditions: {
    // Integer Field Conditions
    1: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Greater Than', value: '>' },
      { id: '4', label: 'Greater Than or Equal To', value: '>=' },
      { id: '5', label: 'Less Than', value: '<' },
      { id: '6', label: 'Less Than or Equal To', value: '<=' },
      { id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // Float Field Conditions
    2: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Greater Than', value: '>' },
      { id: '4', label: 'Greater Than or Equal To', value: '>=' },
      { id: '5', label: 'Less Than', value: '<' },
      { id: '6', label: 'Less Than or Equal To', value: '<=' },
      { id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // String Field Conditions
    3: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Contains', value: 'contains' },
      { id: '4', label: 'Does Not Contain', value: 'not_contains' },
      { id: '5', label: 'Starts With', value: 'starts_with' },
      { id: '6', label: 'Ends With', value: 'ends_with' },
      { id: '7', label: 'Is Empty', value: 'is_empty' },
      { id: '8', label: 'Is Not Empty', value: 'is_not_empty' },
      { id: '9', label: 'Is Null', value: 'is_null' },
      { id: '10', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // Big String Field Conditions
    4: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Contains', value: 'contains' },
      { id: '4', label: 'Does Not Contain', value: 'not_contains' },
      { id: '5', label: 'Starts With', value: 'starts_with' },
      { id: '6', label: 'Ends With', value: 'ends_with' },
      { id: '7', label: 'Is Empty', value: 'is_empty' },
      { id: '8', label: 'Is Not Empty', value: 'is_not_empty' },
      { id: '9', label: 'Is Null', value: 'is_null' },
      { id: '10', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // Date Field Conditions
    5: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Before', value: '<' },
      { id: '4', label: 'On or Before', value: '<=' },
      { id: '5', label: 'After', value: '>' },
      { id: '6', label: 'On or After', value: '>=' },
      { id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // DateTime Field Conditions
    6: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Before', value: '<' },
      { id: '4', label: 'On or Before', value: '<=' },
      { id: '5', label: 'After', value: '>' },
      { id: '6', label: 'On or After', value: '>=' },
      { id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // DateTime Field Conditions
    7: [
      { id: '1', label: 'Equals', value: '=' },
      { id: '2', label: 'Not Equals', value: '!=' },
      { id: '3', label: 'Before', value: '<' },
      { id: '4', label: 'On or Before', value: '<=' },
      { id: '5', label: 'After', value: '>' },
      { id: '6', label: 'On or After', value: '>=' },
      { id: '7', label: 'Is Null', value: 'is_null' },
      { id: '8', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // Integer Range Field Conditions
    8: [
      { id: '1', label: 'Between', value: 'between' },
      { id: '2', label: 'Not Between', value: 'not_between' },
      { id: '3', label: 'Is Null', value: 'is_null' },
      { id: '4', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // Float Range Field Conditions
    9: [
      { id: '1', label: 'Between', value: 'between' },
      { id: '2', label: 'Not Between', value: 'not_between' },
      { id: '3', label: 'Is Null', value: 'is_null' },
      { id: '4', label: 'Is Not Null', value: 'is_not_null' },
    ],

    // Date Range Field Conditions
    10: [
      { id: '1', label: 'Between', value: 'between' },
      { id: '2', label: 'Not Between', value: 'not_between' },
      { id: '3', label: 'Is Null', value: 'is_null' },
      { id: '4', label: 'Is Not Null', value: 'is_not_null' },
    ],
  },
  field_type: {
    1: 'number',
    2: 'number',
    3: 'text',
    4: 'text',
    5: 'date',
    6: 'datetime-local',
    7: 'datetime-local',
    8: 'number',
    9: 'number',
    10: 'date',
  },
  wizard_type: [
    {
      label: 'Chart',
      value: 'chart',
    },
    {
      label: 'Static',
      value: 'static',
    },
  ],
  WIZARD_TYPES: {
    CHART: 'chart',
    STATIC: 'static',
  },
};
